# Generated by Django 3.1.13 on 2021-07-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmnews', '0002_post_cover_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_img',
            field=models.ImageField(blank=True, null=True, upload_to='cover/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
