# Generated by Django 3.1.13 on 2021-07-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmnews', '0003_auto_20210727_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_img',
            field=models.ImageField(blank=True, null=True, upload_to='cover/', verbose_name='Foto Sampul'),
        ),
    ]
